<?php

namespace HuntkingdomBundle\Repository;

/**
 * AnnonceMobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceMobRepository extends \Doctrine\ORM\EntityRepository
{
}
