<?php

namespace HuntkingdomBundle\Repository;

/**
 * CommentaireMobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireMobRepository extends \Doctrine\ORM\EntityRepository
{
}
