<?php

namespace HuntkingdomBundle\Repository;

/**
 * PubliciteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubliciteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPubAimer($id,$user)
    {
        $query=$this->getEntityManager()->createQuery("SELECT i FROM HuntkingdomBundle:PubliciteAimer i 
WHERE i.idPublicite=$id AND i.idUser= $user");
        return $query->getResult();
    }
    public function  countPromo(){
        $query=$this->getEntityManager()->createQuery("SELECT COUNT(i) FROM HuntkingdomBundle:Promotion i 
WHERE i.date_debut= DATE(NOW())");

        return $query->getResult();
    }

}
