<?php

namespace HuntkingdomBundle\Repository;

/**
 * ReclamationMobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationMobRepository extends \Doctrine\ORM\EntityRepository
{
}
