<?php

namespace HuntkingdomBundle\Repository;

/**
 * RepMobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepMobRepository extends \Doctrine\ORM\EntityRepository
{
}
